# Generated by Django 6.0.2 on 2026-03-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="Post",
        ),
    ]
