# Generated by Django 6.0.2 on 2026-03-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_blog_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publication_indicator",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
