# Generated by Django 6.0.2 on 2026-03-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_publication_indicator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/photo",
                verbose_name="Изображение",
            ),
        ),
    ]
