# Generated by Django 6.0.2 on 2026-03-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="purchase_price",
            new_name="price",
        ),
    ]
