# Generated by Django 6.0.2 on 2026-03-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/photo",
                verbose_name="Изображение",
            ),
        ),
    ]
