# Generated by Django 6.0.2 on 2026-04-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_publication",
            field=models.BooleanField(default=False, verbose_name="Опубликовать"),
        ),
    ]
